baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Riccardo Pastori blog'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[mediaTypes."text/html"]
  suffixes = ["html", "gohtml"]

[markup.tableOfContents]
  startLevel = 2

[params.author]
  name = "Riccardo Pastori"

[params.icons]
  default = "icons/placeholder-duotone.svg"

[params.contact]
  email = "ricpastori@icloud.com"

[params.social]
  github   = "https://github.com/ricpastori"
  linkedin = "https://www.linkedin.com/in/riccardo-pastori/"